Added interview question model and repository
3PillarGlobal-Ostrava/interview-app-api pull request #8
Opened 2022-01-21 09:11 UTC by TomasNiemczyk98

## Summary

Added interview question model and repository

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactoring (non-breaking change to code and structure)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-01-21 09:33 UTC, PlesnikJakub requested changes
There are small changes required. Basically, it's just namespaces and formatting, other than that it looks good 😊 Please make those small changes then we can ship it.

2022-01-21 09:33 UTC, PlesnikJakub commented on src/WebApi/Application/Repositories/IInterviewQuestionRepository.cs
> +namespace Application.Repositories
Let's convert all namespaces to the file scoped version. We will enforce it as a standard across whole repository. 

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces

2022-01-21 09:33 UTC, PlesnikJakub commented on src/WebApi/Domain/Models/InterviewQuestionModel.cs
> +        public string Title { get; set; }
Please fix formatting and add newlines between props so its consistent between Model and Entity class 😊

2022-01-21 11:14 UTC, PlesnikJakub approved these changes
LGTMT 🚀

2022-01-21 11:16 UTC, merged

2022-01-24 11:21 UTC, petrspelos commented
@TomasNiemczyk98 feel free to delete the feature branch if it's not needed. ☺️